/* Simple Lua generator for CPT200 */

// 既存のLuaジェネレーターがあれば拡張、無ければ新規作成
Blockly.Lua = Blockly.Lua || new Blockly.Generator('Lua');

Blockly.Lua.ORDER_ATOMIC = 0;
Blockly.Lua.ORDER_NONE = 99;

Blockly.Lua.init = function(workspace) {
  // 変数の初期化（Luaローカル変数）
  if (!Blockly.Lua.definitions_) Blockly.Lua.definitions_ = Object.create(null);
  Blockly.Lua.definitions_['header'] = '-- Generated by CPT200 Blockly Lua Builder\n';
};

Blockly.Lua.finish = function(code) {
  const defs = Object.values(Blockly.Lua.definitions_ || {}).join('\n');
  Blockly.Lua.definitions_ = Object.create(null);
  return defs + '\n' + code;
};

Blockly.Lua.scrub_ = function(block, code) {
  const comment = block.getCommentText();
  if (comment) {
    code = '-- ' + comment.replace(/\n/g, '\n-- ') + '\n' + code;
  }
  return code;
};

// Program root → BOOT / LOOP 関数の生成
Blockly.Lua['cpt_program_root'] = function(block) {
  const bootStmts = Blockly.Lua.statementToCode(block, 'BOOT');
  const loopStmts = Blockly.Lua.statementToCode(block, 'LOOP');
  let code = '';
  code += 'function BOOT()\n' + (bootStmts || '') + 'end\n\n';
  code += 'function LOOP()\n' + (loopStmts || '') + 'end\n\n';
  return code;
};

// print(text,x,y,color)
Blockly.Lua['cpt_print'] = function(block) {
  const t = Blockly.Lua.valueToCode(block, 'TEXT', Blockly.Lua.ORDER_NONE) || '""';
  const x = Blockly.Lua.valueToCode(block, 'X', Blockly.Lua.ORDER_NONE) || '0';
  const y = Blockly.Lua.valueToCode(block, 'Y', Blockly.Lua.ORDER_NONE) || '0';
  const c = Blockly.Lua.valueToCode(block, 'COLOR', Blockly.Lua.ORDER_NONE) || '0';
  return 'print(' + t + ',' + x + ',' + y + ',' + c + ')\n';
};

// pix(x,y,color)
Blockly.Lua['cpt_pix'] = function(block) {
  const x = Blockly.Lua.valueToCode(block, 'X', Blockly.Lua.ORDER_NONE) || '0';
  const y = Blockly.Lua.valueToCode(block, 'Y', Blockly.Lua.ORDER_NONE) || '0';
  const c = Blockly.Lua.valueToCode(block, 'COLOR', Blockly.Lua.ORDER_NONE) || '0';
  return 'pix(' + x + ',' + y + ',' + c + ')\n';
};

// rect(x,y,w,h,color)
Blockly.Lua['cpt_rect'] = function(block) {
  const x = Blockly.Lua.valueToCode(block, 'X', Blockly.Lua.ORDER_NONE) || '0';
  const y = Blockly.Lua.valueToCode(block, 'Y', Blockly.Lua.ORDER_NONE) || '0';
  const w = Blockly.Lua.valueToCode(block, 'W', Blockly.Lua.ORDER_NONE) || '0';
  const h = Blockly.Lua.valueToCode(block, 'H', Blockly.Lua.ORDER_NONE) || '0';
  const c = Blockly.Lua.valueToCode(block, 'COLOR', Blockly.Lua.ORDER_NONE) || '0';
  return 'rect(' + x + ',' + y + ',' + w + ',' + h + ',' + c + ')\n';
};

// line(xs,ys,xe,ye,color)
Blockly.Lua['cpt_line'] = function(block) {
  const xs = Blockly.Lua.valueToCode(block, 'XS', Blockly.Lua.ORDER_NONE) || '0';
  const ys = Blockly.Lua.valueToCode(block, 'YS', Blockly.Lua.ORDER_NONE) || '0';
  const xe = Blockly.Lua.valueToCode(block, 'XE', Blockly.Lua.ORDER_NONE) || '0';
  const ye = Blockly.Lua.valueToCode(block, 'YE', Blockly.Lua.ORDER_NONE) || '0';
  const c = Blockly.Lua.valueToCode(block, 'COLOR', Blockly.Lua.ORDER_NONE) || '0';
  return 'line(' + xs + ',' + ys + ',' + xe + ',' + ye + ',' + c + ')\n';
};

// rgb(r,g,b) → number
Blockly.Lua['cpt_rgb'] = function(block) {
  const r = Blockly.Lua.valueToCode(block, 'R', Blockly.Lua.ORDER_NONE) || '0';
  const g = Blockly.Lua.valueToCode(block, 'G', Blockly.Lua.ORDER_NONE) || '0';
  const b = Blockly.Lua.valueToCode(block, 'B', Blockly.Lua.ORDER_NONE) || '0';
  const code = 'rgb(' + r + ',' + g + ',' + b + ')';
  return [code, Blockly.Lua.ORDER_ATOMIC];
};

// rgbd(x,y,r,g,b) → number
Blockly.Lua['cpt_rgbd'] = function(block) {
  const x = Blockly.Lua.valueToCode(block, 'X', Blockly.Lua.ORDER_NONE) || '0';
  const y = Blockly.Lua.valueToCode(block, 'Y', Blockly.Lua.ORDER_NONE) || '0';
  const r = Blockly.Lua.valueToCode(block, 'R', Blockly.Lua.ORDER_NONE) || '0';
  const g = Blockly.Lua.valueToCode(block, 'G', Blockly.Lua.ORDER_NONE) || '0';
  const b = Blockly.Lua.valueToCode(block, 'B', Blockly.Lua.ORDER_NONE) || '0';
  const code = 'rgbd(' + x + ',' + y + ',' + r + ',' + g + ',' + b + ')';
  return [code, Blockly.Lua.ORDER_ATOMIC];
};

// cls(color)
Blockly.Lua['cpt_cls'] = function(block) {
  const c = Blockly.Lua.valueToCode(block, 'COLOR', Blockly.Lua.ORDER_NONE) || '0';
  return 'cls(' + c + ')\n';
};

// screen(mode)
Blockly.Lua['cpt_screen'] = function(block) {
  const m = Blockly.Lua.valueToCode(block, 'MODE', Blockly.Lua.ORDER_NONE) || '0';
  return 'screen(' + m + ')\n';
};

// spr(index, enabled, x, y, rotation)
Blockly.Lua['cpt_spr'] = function(block) {
  const i = Blockly.Lua.valueToCode(block, 'INDEX', Blockly.Lua.ORDER_NONE) || '0';
  const en = block.getFieldValue('ENABLED') === 'TRUE' ? 'true' : 'false';
  const x = Blockly.Lua.valueToCode(block, 'X', Blockly.Lua.ORDER_NONE) || '0';
  const y = Blockly.Lua.valueToCode(block, 'Y', Blockly.Lua.ORDER_NONE) || '0';
  const rot = Blockly.Lua.valueToCode(block, 'ROT', Blockly.Lua.ORDER_NONE) || '0';
  return 'spr(' + i + ', ' + en + ', ' + x + ', ' + y + ', ' + rot + ')\n';
};

// time() → number
Blockly.Lua['cpt_time'] = function(block) {
  return ['time()', Blockly.Lua.ORDER_ATOMIC];
};

// key(keycode) → number
Blockly.Lua['cpt_key'] = function(block) {
  const k = Blockly.Lua.valueToCode(block, 'KEYCODE', Blockly.Lua.ORDER_NONE) || '0';
  return ['key(' + k + ')', Blockly.Lua.ORDER_ATOMIC];
};

// mouse() → local var assign
Blockly.Lua['cpt_mouse_assign'] = function(block) {
  const vx = block.getFieldValue('VX') || 'mx';
  const vy = block.getFieldValue('VY') || 'my';
  const vb = block.getFieldValue('VB') || 'mb';
  return 'local ' + vx + ',' + vy + ',' + vb + ' = mouse()\n';
};
