name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
jobs:
  debug-build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          ../build-scripts/doDebugBuild.bat
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CPTTracker.exe
          path: ${{ github.workspace }}/build/CPTTracker.exe
