name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  debug-build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --parallel         
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cpttracker
          path: ${{ github.workspace }}/build/cpttracker.exe
  debug-build-for-wasm:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          cd ${{ github.workspace }}
          ./lib/emsdk/emsdk install latest
          ./lib/emsdk/emsdk activate latest
          source ./lib/emsdk/emsdk_env.sh
          mkdir build
          emcmake cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_WASM=ON -DCMAKE_C_COMPILER=${{ github.workspace }}/lib/emsdk/upstream/emscripten/emcc -DCMAKE_CXX_COMPILER=${{ github.workspace }}/lib/emsdk/upstream/emscripten/em++
          cmake --build build --parallel         
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: './build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  debug-build-for-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --parallel         
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cpttracker
          path: ${{ github.workspace }}/build/cpttracker