name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
jobs:
  debug-build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -S .. -B . -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
          mingw32-make -j4          
