name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
jobs:
  debug-build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --parallel         
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cpt100
          path: ${{ github.workspace }}/build/cpt100.exe
