name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
jobs:
  debug-build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Install Latest MinGW
        run: |
          choco install mingw
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
          mingw32-make build -j4
          
