name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
jobs:
  debug-build-for-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          mkdir build
          build-scripts\\doDebugBuild.bat
          
