name: build
run-name: Main build by ${{ github.actor }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Toolchains
        run: |
          sudo apt install mingw-w64
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          sh build-scripts/doDebugBuild.sh
