name: build
run-name: Debug build by ${{ github.actor }}
on: [push]
jobs:
  debug-build-for-windows-using-mingw:
    runs-on: ubuntu-latest
    steps:
      - name: Install Toolchains
        run: |
          sudo apt install mingw-w64 ninja-build
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          sh build-scripts/doDebugBuild.sh
